controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Route simple
# route_name:
#     path: /mon-url
#     controller: App\Controller\MonController::maMethode
#     methods: [GET]

# Route avec paramètre
calcul_route:
    path: /calcul/{a}
    controller: App\Controller\MainController::indexter
    methods: [GET]
    requirements:
        # a: '\d+'
        a: "[1-9][0-9]?|100"

hello_route:
    path: /hello/{prenom}
    controller: App\Controller\FormController::hello
    methods: [GET]
    requirements:
        prenom: "[A-Za-z]+"

list_tuteur_route:
    path: /tuteurs/{prenom}
    controller: App\Controller\FormController::hello
    methods: [GET]
    requirements:
        prenom: "[A-Za-z]+"

list_tuteurs_route:
    path: /tuteurs
    controller: App\Controller\TuteurController::index
    methods: [GET]

search_tutor_route:
    path: /search_tuteur
    controller: App\Controller\FormController::search
    methods: [GET]

post_search_tutor_route:
    path: /search_tuteur/post
    controller: App\Controller\FormController::verify
    methods: [POST]

students_route:
    path: /students
    controller: App\Controller\StudentController::students
    methods: [GET]

app_tuteur_show:
    path: /tuteurs/{id}
    controller: App\Controller\TuteurController::show
    methods: [GET]
    
app_sujets:
    path: /sujets
    controller: App\Controller\TuteurController::sujets
    methods: [GET]

# for auth
app_login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: [GET, POST]

# app_register:
#     path: /register
#     controller: App\Controller\AuthController::register
#     methods: [GET, POST]

app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout
    methods: [GET]

app_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index
    methods: [GET]

student_add:
    path: /students/add
    controller: App\Controller\EtudiantController::add
    methods: [GET, POST]

student_edit:
    path: /students/edit/{id}
    controller: App\Controller\EtudiantController::edit
    methods: [GET, POST]

# for visites
etudiant_visites:
    path: /students/{id}/visites
    controller: App\Controller\VisiteController::visites
    methods: [GET]

visite_add:
    path: /students/{id}/visites/new
    controller: App\Controller\VisiteController::add
    methods: [GET, POST]

visite_edit:
    path: /visites/{id}/edit
    controller: App\Controller\VisiteController::edit
    methods: [GET, POST]

visite_compte_rendu:
    path: /visites/{id}/compte-rendu
    controller: App\Controller\VisiteController::compteRendu
    methods: [GET, POST]

visite_compte_rendu_pdf:
    path: /visites/{id}/compte-rendu/pdf
    controller: App\Controller\VisiteController::exportPdf
    methods: [GET, POST]

